//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseEntities
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class DetailNomenclature : IRateable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DetailNomenclature()
        {
            this.RateSet = new HashSet<Rate>();
            Name = "empty";
            DetailType = TypeOfDetail.None;
        }
        public DetailNomenclature(string name, string description, TypeOfDetail type) : base()
        {
            Name = name;
            Description = description;
            DetailType = type;
        }
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public TypeOfDetail DetailType { get; set; }
        public double TotalRate { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rate> RateSet { get; set; }
    }
}
